export const globalSchoolsData = [
{name: "Chris Anglican School", students: 68, teachers: 5},
{name: "Jonworth schools", students: 45, teachers: 3},
{name: "Standard Wisdom International School", students: 110, teachers: 5},
{name: "Charlotte Vidercare School", students: 25, teachers: 2},
{name: "Motherwell School", students: 60, teachers: 3},
{name: "Finger of God Academy", students: 38, teachers: 3},
{name: "Charisma Anglican School", students: 21, teachers: 2},
{name: "Friendswood College", students: 40, teachers: 2},
{name: "Charlotte International School", students: 18, teachers: 1},
{name: "Hand of God Academy", students: 68, teachers: 4},
{name: "WhiteSands International School", students: 29, teachers: 3},
{name: "Okun-Ajah Community School", students: 50, teachers: 5},
{name: "Illaro Grammer School", students: 72, teachers: 7},
{name: "Greatvile College", students: 76, teachers: 5},
{name: "Ismahila Community School", students: 20, teachers: 2},

{name: "Adebayo Mokuolu College", students: 48, teachers: 3},
{name: "Southgold College", students: 24, teachers: 3},
{name: "Emperor International Schools", students: 40, teachers: 4},
{name: "Anglican Grammar School", students: 61, teachers: 6},
{name: "Eminence College", students: 58, teachers: 6},
{name: "Goldmine Schools", students: 40, teachers: 5},
{name: "Edidot College", students: 42, teachers: 2},
{name: "Golden Foundation College", students: 23, teachers: 2},
{name: "Moyi Comprehensive College", students: 15, teachers: 1},
{name: "Zabras Royal College", students: 60, teachers: 6},
{name: "Tos Vvi Precious College", students: 80, teachers: 7},
{name: "St Emma Comprehensive College", students: 68, teachers: 6},
{name: "Abcel Academy", students: 31, teachers: 2},
{name: "Chresol Schools", students: 20, teachers: 2},
{name: "Attwool School", students: 23, teachers: 1},

{name: "Maryanne College", students: 40, teachers: 5},
{name: "Divine College ", students: 26, teachers: 3},
{name: "Spring of Life School", students: 27, teachers: 1},
{name: "Debam College ", students: 26, teachers: 2},
{name: "MacDonald Trevan Intl School", students: 79, teachers: 6},
{name: "Flourish Hall International ", students: 57, teachers: 6},
{name: "Deaton Villa ", students: 51, teachers: 5},
{name: "Dorras College", students: 60, teachers: 5},
{name: "Muslim Pride School", students: 48, teachers: 4},
{name: "UnionVille School", students: 20, teachers: 2},
{name: "Catony Royal School", students: 16, teachers: 1},
{name: "FVC Global Academy", students: 30, teachers: 3},
{name: "Lead Faith School ", students: 28, teachers: 4},
{name: "Royal Cedars School", students: 63, teachers: 7},

{name: "Lekki Crystal Spring ", students: 46, teachers: 3 },
{name: "Toppseed School", students: 28, teachers: 1 },
{name: "Leaners Shield Height School", students: 102, teachers: 8 },
{name: "Student Development Academy", students: 14, teachers: 1 },
{name: "Leaers Ladder Int'l School", students: 25, teachers: 1 },
{name: "Ivy Diamond School", students: 20, teachers: 1 },
{name: "Glorious Ambassadors School", students: 32, teachers: 2 },
{name: "Laurels Foundation school", students: 35, teachers: 2 },
{name: "Chogap ", students: 80, teachers: 6 },
{name: "Convenant Child Academy", students: 40, teachers: 5 },
{name: "Dominion Citadel School", students:22, teachers: 2 },
{name: "The Living Spring SChool", students: 18, teachers: 2 },
{name: "Moral Esteem College ", students: 60, teachers: 6 },
{name: "Producers Academy", students: 30, teachers: 2 },
{name: "Padre Monti College", students: 45, teachers: 3} ,
{name: "The Prevail Height College", students: 47, teachers: 3 },
{name: "Spring Sprout School", students: 70, teachers: 5 },
{name: "Shanjerert Schools ", students: 68, teachers: 6 },
{name: "The White Dove", students: 65, teachers: 5 },
{name: "Kayron International School", students: 49, teachers: 4 },
{name: "Creative Mind School", students: 50, teachers: 3 },
{name: "Glideville School", students: 50, teachers: 5 } ,
{name: "Viridian Comprehensive College", students: 28, teachers: 2 },
{name: "Splendid Steps School", students: 26, teachers: 1 },
{name: "Mathbridge  Schools", students: 35, teachers: 3 } ,
{name: "Gabliz School", students: 56, teachers: 5 },
{name: "School Masters Academy", students: 62, teachers: 4 },
{name: "Bethel Comprehensive College", students: 22, teachers: 2 },
{name: "Starways College", students: 10, teachers: 1 } ,
{name: "Wisdom foundation College", students: 28, teachers: 2 },
]