export const globalSchoolsData = [
{name: "Maryanne College"},
{name: "Divine College "},
{name: "Spring of Life School"},
{name: "Debam College "},
{name: "MacDonald Trevan Intl School"},
{name: "Flourish Hall International "},
{name: "Deaton Villa "},
{name: "Dorras College"},
{name: "Muslim Pride School"},
{name: "UnionVille School"},
{name: "Catony Royal School"},
{name: "FVC Global Academy"},
{name: "Lead Faith School "},
{name: "Royal Cedars School"},

{name: "Lekki Crystal Spring " },
{name: "Toppseed School" },
{name: "Leaners Shield Height School" },
{name: "Student Development Academy" },
{name: "Leaers Ladder Int'l School" },
{name: "Ivy Diamond School" },
{name: "Glorious Ambassadors School" },
{name: "Laurels Foundation school" },
{name: "Chogap " },
{name: "Convenant Child Academy" },
{name: "Dominion Citadel School" },
{name: "The Living Spring SChool" },
{name: "Moral Esteem College " },
{name: "Producers Academy" },
{name: "Padre Monti College"} ,
{name: "The Prevail Height College" },
{name: "Spring Sprout School" },
{name: "Shanjerert Schools " },
{name: "The White Dove" },
{name: "Kayron International School" },
{name: "Creative Mind School" },
{name: "Glideville School" } ,
{name: "Viridian Comprehensive College" },
{name: "Splendid Steps School" },
{name: "Mathbridge  Schools" } ,
{name: "Gabliz School" },
{name: "School Masters Academy" },
{name: "Bethel Comprehensive College" },
{name: "Starways College" } ,
{name: "Wisdom foundation College" },
]